services:
  db:
    image: postgres:16-alpine
    container_name: wse_math_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: wse_math_student
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: wse_math_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@wse.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
